name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run tests
        run: pytest life_expectancy --cov

      - name: Run pylint
        run: pylint life_expectancy.cleaning