name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run tests
        run: pytest --cov-report html --cov=life_expectancy

      - name: Run pylint
        run: |
          pylint life_expectancy.data_cleaning
          pylint life_expectancy.data_loading
          pylint life_expectancy.main
          pylint life_expectancy.region
